version: '2'
services:
    app:
        image: nginx:1.23.1-alpine
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./source:/usr/share/nginx/
        ports:
            - "5000:80"
        